### ISSUE TITLE
Cannot install package on .NETFramework,Version=v4.5.2.

### ISSUE THREAD

**Issue by vagadoo** [yolofy/Connectors.OBP#1]
Hi,

I tried to install the package on my project but it gives me this error:

Install-Package : Could not install package 'Connectors.OBP 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package 
does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Connectors.OBP
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by yolofy** [comment]
Hi. I downgraded to net452, should be working now. Please install the 1.0.1 version
